# Generated by Django 4.0.2 on 2022-10-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobber', '0002_accesskey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
